name: example run
on: [push,workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.1]
    steps:
      - name: Install dep
        run:  pip3 install simpy
      - name: Run code
        run: python3 example.py

    
